import { CountryCostData } from './calculator/calculator';

export const FALLBACK_COUNTRIES: readonly CountryCostData[] = [
    // Europe
    { code: 'DE', name: 'Germany', nameDE: 'Deutschland', continent: 'Europe', costs: { accommodation: { budget: 30, midrange: 80, luxury: 200 }, food: { budget: 20, midrange: 40, luxury: 80 }, transport: 10, activities: 25, flightFromEU: 80 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-1784&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/de/', airbnbUrl: 'https://www.airbnb.com/s/Germany', getYourGuideUrl: 'https://www.getyourguide.com/germany-l36/' },
    { code: 'FR', name: 'France', nameDE: 'Frankreich', continent: 'Europe', costs: { accommodation: { budget: 35, midrange: 100, luxury: 250 }, food: { budget: 22, midrange: 45, luxury: 90 }, transport: 12, activities: 30, flightFromEU: 80 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-1454&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/fr/', airbnbUrl: 'https://www.airbnb.com/s/France', getYourGuideUrl: 'https://www.getyourguide.com/france-l1/' },
    { code: 'ES', name: 'Spain', nameDE: 'Spanien', continent: 'Europe', costs: { accommodation: { budget: 25, midrange: 75, luxury: 180 }, food: { budget: 18, midrange: 35, luxury: 70 }, transport: 8, activities: 22, flightFromEU: 80 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-2126&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/es/', airbnbUrl: 'https://www.airbnb.com/s/Spain', getYourGuideUrl: 'https://www.getyourguide.com/spain-l1/' },
    { code: 'IT', name: 'Italy', nameDE: 'Italien', continent: 'Europe', costs: { accommodation: { budget: 30, midrange: 90, luxury: 220 }, food: { budget: 20, midrange: 40, luxury: 85 }, transport: 10, activities: 28, flightFromEU: 80 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-1591&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/it/', airbnbUrl: 'https://www.airbnb.com/s/Italy', getYourGuideUrl: 'https://www.getyourguide.com/italy-l93/' },
    { code: 'PT', name: 'Portugal', nameDE: 'Portugal', continent: 'Europe', costs: { accommodation: { budget: 22, midrange: 65, luxury: 160 }, food: { budget: 15, midrange: 30, luxury: 65 }, transport: 7, activities: 18, flightFromEU: 80 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-1969&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/pt/', airbnbUrl: 'https://www.airbnb.com/s/Portugal', getYourGuideUrl: 'https://www.getyourguide.com/portugal-l193/' },
    { code: 'GR', name: 'Greece', nameDE: 'Griechenland', continent: 'Europe', costs: { accommodation: { budget: 22, midrange: 70, luxury: 180 }, food: { budget: 15, midrange: 28, luxury: 60 }, transport: 7, activities: 20, flightFromEU: 100 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-1521&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/gr/', airbnbUrl: 'https://www.airbnb.com/s/Greece', getYourGuideUrl: 'https://www.getyourguide.com/greece-l54/' },
    { code: 'HR', name: 'Croatia', nameDE: 'Kroatien', continent: 'Europe', costs: { accommodation: { budget: 20, midrange: 65, luxury: 160 }, food: { budget: 15, midrange: 28, luxury: 55 }, transport: 7, activities: 18, flightFromEU: 100 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-89&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/hr/', airbnbUrl: 'https://www.airbnb.com/s/Croatia', getYourGuideUrl: 'https://www.getyourguide.com/croatia-l132/' },
    { code: 'PL', name: 'Poland', nameDE: 'Polen', continent: 'Europe', costs: { accommodation: { budget: 15, midrange: 45, luxury: 120 }, food: { budget: 10, midrange: 18, luxury: 40 }, transport: 5, activities: 12, flightFromEU: 80 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-1956&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/pl/', airbnbUrl: 'https://www.airbnb.com/s/Poland', getYourGuideUrl: 'https://www.getyourguide.com/poland-l211/' },
    { code: 'CZ', name: 'Czech Republic', nameDE: 'Tschechien', continent: 'Europe', costs: { accommodation: { budget: 15, midrange: 50, luxury: 130 }, food: { budget: 10, midrange: 18, luxury: 40 }, transport: 4, activities: 12, flightFromEU: 80 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-1092&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/cz/', airbnbUrl: 'https://www.airbnb.com/s/Czech-Republic', getYourGuideUrl: 'https://www.getyourguide.com/czech-republic-l104/' },
    { code: 'AT', name: 'Austria', nameDE: 'Österreich', continent: 'Europe', costs: { accommodation: { budget: 28, midrange: 80, luxury: 200 }, food: { budget: 18, midrange: 35, luxury: 75 }, transport: 10, activities: 25, flightFromEU: 80 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-1587&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/at/', airbnbUrl: 'https://www.airbnb.com/s/Austria', getYourGuideUrl: 'https://www.getyourguide.com/austria-l73/' },
    { code: 'CH', name: 'Switzerland', nameDE: 'Schweiz', continent: 'Europe', costs: { accommodation: { budget: 50, midrange: 150, luxury: 350 }, food: { budget: 30, midrange: 60, luxury: 120 }, transport: 20, activities: 40, flightFromEU: 80 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-2168&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/ch/', airbnbUrl: 'https://www.airbnb.com/s/Switzerland', getYourGuideUrl: 'https://www.getyourguide.com/switzerland-l178/' },
    { code: 'IS', name: 'Iceland', nameDE: 'Island', continent: 'Europe', costs: { accommodation: { budget: 45, midrange: 130, luxury: 300 }, food: { budget: 30, midrange: 55, luxury: 110 }, transport: 20, activities: 50, flightFromEU: 180 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-139137&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/is/', airbnbUrl: 'https://www.airbnb.com/s/Iceland', getYourGuideUrl: 'https://www.getyourguide.com/iceland-l191/' },

    // Asia
    { code: 'TH', name: 'Thailand', nameDE: 'Thailand', continent: 'Asia', costs: { accommodation: { budget: 12, midrange: 40, luxury: 120 }, food: { budget: 8, midrange: 18, luxury: 40 }, transport: 5, activities: 15, flightFromEU: 550 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-3247&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/th/', airbnbUrl: 'https://www.airbnb.com/s/Thailand', getYourGuideUrl: 'https://www.getyourguide.com/thailand-l87/' },
    { code: 'JP', name: 'Japan', nameDE: 'Japan', continent: 'Asia', costs: { accommodation: { budget: 25, midrange: 80, luxury: 220 }, food: { budget: 15, midrange: 30, luxury: 70 }, transport: 12, activities: 25, flightFromEU: 700 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-246227&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/jp/', airbnbUrl: 'https://www.airbnb.com/s/Japan', getYourGuideUrl: 'https://www.getyourguide.com/japan-l115/' },
    { code: 'ID', name: 'Indonesia (Bali)', nameDE: 'Indonesien (Bali)', continent: 'Asia', costs: { accommodation: { budget: 15, midrange: 45, luxury: 130 }, food: { budget: 7, midrange: 15, luxury: 35 }, transport: 5, activities: 15, flightFromEU: 650 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-1440&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/id/', airbnbUrl: 'https://www.airbnb.com/s/Bali--Indonesia', getYourGuideUrl: 'https://www.getyourguide.com/bali-l67/' },
    { code: 'VN', name: 'Vietnam', nameDE: 'Vietnam', continent: 'Asia', costs: { accommodation: { budget: 10, midrange: 35, luxury: 100 }, food: { budget: 6, midrange: 12, luxury: 30 }, transport: 4, activities: 12, flightFromEU: 600 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-3386&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/vn/', airbnbUrl: 'https://www.airbnb.com/s/Vietnam', getYourGuideUrl: 'https://www.getyourguide.com/vietnam-l190/' },
    { code: 'IN', name: 'India', nameDE: 'Indien', continent: 'Asia', costs: { accommodation: { budget: 10, midrange: 35, luxury: 100 }, food: { budget: 5, midrange: 12, luxury: 30 }, transport: 4, activities: 12, flightFromEU: 550 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-2092950&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/in/', airbnbUrl: 'https://www.airbnb.com/s/India', getYourGuideUrl: 'https://www.getyourguide.com/india-l126/' },
    { code: 'SG', name: 'Singapore', nameDE: 'Singapur', continent: 'Asia', costs: { accommodation: { budget: 35, midrange: 120, luxury: 300 }, food: { budget: 10, midrange: 25, luxury: 60 }, transport: 8, activities: 30, flightFromEU: 650 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-73635&dest_type=city', skyscannerUrl: 'https://www.skyscanner.de/fluege/sg/', airbnbUrl: 'https://www.airbnb.com/s/Singapore', getYourGuideUrl: 'https://www.getyourguide.com/singapore-l6/' },
    { code: 'AE', name: 'Dubai / UAE', nameDE: 'Dubai / VAE', continent: 'Asia', costs: { accommodation: { budget: 40, midrange: 130, luxury: 400 }, food: { budget: 18, midrange: 40, luxury: 100 }, transport: 12, activities: 45, flightFromEU: 350 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-782831&dest_type=city', skyscannerUrl: 'https://www.skyscanner.de/fluege/ae/', airbnbUrl: 'https://www.airbnb.com/s/Dubai--United-Arab-Emirates', getYourGuideUrl: 'https://www.getyourguide.com/dubai-l539/' },
    { code: 'TR', name: 'Turkey', nameDE: 'Türkei', continent: 'Asia', costs: { accommodation: { budget: 15, midrange: 50, luxury: 130 }, food: { budget: 8, midrange: 18, luxury: 40 }, transport: 5, activities: 15, flightFromEU: 150 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-3245&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/tr/', airbnbUrl: 'https://www.airbnb.com/s/Turkey', getYourGuideUrl: 'https://www.getyourguide.com/turkey-l76/' },

    // Americas
    { code: 'US', name: 'USA', nameDE: 'USA', continent: 'Americas', costs: { accommodation: { budget: 40, midrange: 120, luxury: 300 }, food: { budget: 20, midrange: 40, luxury: 90 }, transport: 15, activities: 35, flightFromEU: 450 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-3752&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/us/', airbnbUrl: 'https://www.airbnb.com/s/United-States', getYourGuideUrl: 'https://www.getyourguide.com/united-states-l28/' },
    { code: 'MX', name: 'Mexico', nameDE: 'Mexiko', continent: 'Americas', costs: { accommodation: { budget: 18, midrange: 60, luxury: 150 }, food: { budget: 10, midrange: 22, luxury: 50 }, transport: 6, activities: 20, flightFromEU: 500 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-2887&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/mx/', airbnbUrl: 'https://www.airbnb.com/s/Mexico', getYourGuideUrl: 'https://www.getyourguide.com/mexico-l71/' },
    { code: 'CR', name: 'Costa Rica', nameDE: 'Costa Rica', continent: 'Americas', costs: { accommodation: { budget: 20, midrange: 65, luxury: 180 }, food: { budget: 12, midrange: 25, luxury: 55 }, transport: 8, activities: 30, flightFromEU: 650 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-1087&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/cr/', airbnbUrl: 'https://www.airbnb.com/s/Costa-Rica', getYourGuideUrl: 'https://www.getyourguide.com/costa-rica-l77/' },
    { code: 'BR', name: 'Brazil', nameDE: 'Brasilien', continent: 'Americas', costs: { accommodation: { budget: 18, midrange: 55, luxury: 150 }, food: { budget: 10, midrange: 20, luxury: 50 }, transport: 5, activities: 20, flightFromEU: 650 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-672&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/br/', airbnbUrl: 'https://www.airbnb.com/s/Brazil', getYourGuideUrl: 'https://www.getyourguide.com/brazil-l87/' },
    { code: 'AR', name: 'Argentina', nameDE: 'Argentinien', continent: 'Americas', costs: { accommodation: { budget: 15, midrange: 50, luxury: 130 }, food: { budget: 8, midrange: 18, luxury: 45 }, transport: 4, activities: 15, flightFromEU: 700 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-603&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/ar/', airbnbUrl: 'https://www.airbnb.com/s/Argentina', getYourGuideUrl: 'https://www.getyourguide.com/argentina-l57/' },
    { code: 'CA', name: 'Canada', nameDE: 'Kanada', continent: 'Americas', costs: { accommodation: { budget: 35, midrange: 100, luxury: 250 }, food: { budget: 20, midrange: 38, luxury: 80 }, transport: 12, activities: 30, flightFromEU: 500 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-731&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/ca/', airbnbUrl: 'https://www.airbnb.com/s/Canada', getYourGuideUrl: 'https://www.getyourguide.com/canada-l36/' },
    { code: 'PE', name: 'Peru', nameDE: 'Peru', continent: 'Americas', costs: { accommodation: { budget: 15, midrange: 45, luxury: 120 }, food: { budget: 8, midrange: 16, luxury: 40 }, transport: 5, activities: 25, flightFromEU: 700 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-1969&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/pe/', airbnbUrl: 'https://www.airbnb.com/s/Peru', getYourGuideUrl: 'https://www.getyourguide.com/peru-l82/' },

    // Africa
    { code: 'MA', name: 'Morocco', nameDE: 'Marokko', continent: 'Africa', costs: { accommodation: { budget: 15, midrange: 50, luxury: 130 }, food: { budget: 8, midrange: 16, luxury: 35 }, transport: 5, activities: 18, flightFromEU: 150 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-38&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/ma/', airbnbUrl: 'https://www.airbnb.com/s/Morocco', getYourGuideUrl: 'https://www.getyourguide.com/morocco-l30/' },
    { code: 'ZA', name: 'South Africa', nameDE: 'Südafrika', continent: 'Africa', costs: { accommodation: { budget: 20, midrange: 60, luxury: 160 }, food: { budget: 10, midrange: 20, luxury: 50 }, transport: 8, activities: 30, flightFromEU: 600 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-2094&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/za/', airbnbUrl: 'https://www.airbnb.com/s/South-Africa', getYourGuideUrl: 'https://www.getyourguide.com/south-africa-l133/' },
    { code: 'EG', name: 'Egypt', nameDE: 'Ägypten', continent: 'Africa', costs: { accommodation: { budget: 12, midrange: 40, luxury: 110 }, food: { budget: 6, midrange: 14, luxury: 35 }, transport: 4, activities: 15, flightFromEU: 250 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-1408&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/eg/', airbnbUrl: 'https://www.airbnb.com/s/Egypt', getYourGuideUrl: 'https://www.getyourguide.com/egypt-l37/' },
    { code: 'KE', name: 'Kenya', nameDE: 'Kenia', continent: 'Africa', costs: { accommodation: { budget: 20, midrange: 70, luxury: 200 }, food: { budget: 8, midrange: 18, luxury: 40 }, transport: 6, activities: 50, flightFromEU: 550 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-1599&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/ke/', airbnbUrl: 'https://www.airbnb.com/s/Kenya', getYourGuideUrl: 'https://www.getyourguide.com/kenya-l177/' },
    { code: 'TZ', name: 'Tanzania', nameDE: 'Tansania', continent: 'Africa', costs: { accommodation: { budget: 20, midrange: 75, luxury: 220 }, food: { budget: 8, midrange: 18, luxury: 45 }, transport: 8, activities: 60, flightFromEU: 600 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-3247&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/tz/', airbnbUrl: 'https://www.airbnb.com/s/Tanzania', getYourGuideUrl: 'https://www.getyourguide.com/tanzania-l155/' },

    // Oceania
    { code: 'AU', name: 'Australia', nameDE: 'Australien', continent: 'Oceania', costs: { accommodation: { budget: 35, midrange: 100, luxury: 260 }, food: { budget: 20, midrange: 38, luxury: 80 }, transport: 12, activities: 35, flightFromEU: 900 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-600&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/au/', airbnbUrl: 'https://www.airbnb.com/s/Australia', getYourGuideUrl: 'https://www.getyourguide.com/australia-l14/' },
    { code: 'NZ', name: 'New Zealand', nameDE: 'Neuseeland', continent: 'Oceania', costs: { accommodation: { budget: 30, midrange: 90, luxury: 230 }, food: { budget: 18, midrange: 35, luxury: 75 }, transport: 12, activities: 35, flightFromEU: 1100 }, bookingUrl: 'https://www.booking.com/searchresults.html?dest_id=-1944&dest_type=country', skyscannerUrl: 'https://www.skyscanner.de/fluege/nz/', airbnbUrl: 'https://www.airbnb.com/s/New-Zealand', getYourGuideUrl: 'https://www.getyourguide.com/new-zealand-l148/' },
];
