import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export type Language = 'en' | 'de';

@Injectable({
    providedIn: 'root'
})
export class LanguageService {
    private currentLanguage: Language = 'en';
    public language$ = new BehaviorSubject<Language>('en');

    constructor() {
        const savedLanguage = localStorage.getItem('language') as Language | null;
        if (savedLanguage) {
            this.currentLanguage = savedLanguage;
            this.language$.next(this.currentLanguage);
        }
    }

    getCurrentLanguage(): Language {
        return this.currentLanguage;
    }

    toggleLanguage(): void {
        this.currentLanguage = this.currentLanguage === 'en' ? 'de' : 'en';
        localStorage.setItem('language', this.currentLanguage);
        this.language$.next(this.currentLanguage);
    }

    setLanguage(language: Language): void {
        this.currentLanguage = language;
        localStorage.setItem('language', this.currentLanguage);
        this.language$.next(this.currentLanguage);
    }

    getTranslation(key: string): string {
        return this.translations[this.currentLanguage][key] || key;
    }

    private translations: Record<Language, Record<string, string>> = {
        en: {
            // Header Navigation
            'aviation': 'Aviation',
            'travel': 'Travel',
            'photography': 'Photography',
            'myCareer': 'My Career',
            'buyPhotos': 'Buy my photos on adobe stock',
            'aviationGallery': 'Aviation Gallery',
            'aviationSpotterHotels': 'Aviation Spotter Hotels',
            'airlineSim': 'AirlineSim',
            'airGermany': 'Air Germany',
            'airlineSimCeoTools': 'AirlineSim CEO Tools',
            'msfsComparison': 'MSFS Career Addons Comparison',
            'travelInspiration': 'Travel Inspirations',
            'travelGallery': 'Travel Gallery',
            'myVisitedCountries': 'My Visited Countries',
            'menuDescTravelInspiration': 'Travel inspirations from my travels',
            'menuDescVisitedCountries': 'Worldwide travel map',
            'menuDescBudgetCalculator': 'Plan my travel expenses.',
            'searchByBudget': 'Search trips by budget',
            'menuDescSearchByBudget': 'Find destinations that match your budget',
            'menuDescAircraftPhotography': 'Aircraft photography',
            'menuDescSpotterHotels': 'The best spotting hotels',
            'menuDescMsfsComparison': 'Flight simulator comparison',
            'menuDescAviationPhotography': 'Aviation photography',
            'menuDescTravelPhotography': 'Travel photography',
            'menuDescAdobeStock': 'Adobe Stock portfolio',
            'menuDescBrowseProducts': 'Browse products',
            'menuDescAccountSettings': 'Account settings',
            'menuDescDownloads': 'Downloaded files',
            'menuDescOrderHistory': 'Order history',
            'shop': 'Shop',
            'myAccount': 'My Account',
            'profile': 'About me',
            'experience': 'Experience',
            'education': 'Education',
            'skills': 'Skills',
            'projects': 'Projects',
            'testimonials': 'Testimonials',

            // Career Page
            'downloadPDF': 'Download PDF',
            'viewCV': 'View CV',
            'skillsCertifications': 'Skills & Certifications',
            'about': 'About',
            'location': 'Location',
            'email': 'Email',
            'website': 'Website',
            'experiences': 'Experience',
            'educations': 'Education',
            'certifications': 'Certifications',
            'languages': 'Languages',
            'skillsList': 'Skills',
            'projectsList': 'Projects',
            'testimonialsList': 'Testimonials',
            'native': 'Native',
            'fluent': 'Fluent',
            'technologies': 'Technologies',
            'duration': 'Duration',
            'process': 'Process',
            'teamExperience': 'Team Experience',
            'liveTest': 'Live Test',
            'whatColleaguesSay': 'What colleagues say',
            'projectLabel': 'Project:',

            // Budget Calculator
            'budgetCalculator': 'Travel Budget Calculator',
            'calcDestination': 'Destination',
            'calcStartCountry': 'Starting country',
            'calcSelectStartCountry': 'Select departure country...',
            'calcSelectCountry': 'Select a country...',
            'calcDuration': 'Duration (days)',
            'calcPersons': 'Number of persons',
            'calcDisplayCurrency': 'Display currency',
            'calcSeasonLabel': 'Travel season',
            'calcSeasonLow': 'Low season (cheaper)',
            'calcSeasonShoulder': 'Shoulder season (balanced)',
            'calcSeasonHigh': 'High season (peak prices)',
            'calcSeasonHint': 'Season impacts accommodation, activities and flight costs.',
            'calcSeasonUnknown': 'Season not available',
            'calcTravelMonthLabel': 'Travel month',
            'calcTravelMonthHint': 'Pick your travel month. The calculator derives destination season automatically.',
            'calcDerivedSeasonLabel': 'Detected season',
            'calcBufferPercent': 'Safety buffer',
            'calcAccommodation': 'Accommodation type',
            'calcAccBudget': 'Budget (hostel / guesthouse)',
            'calcAccMidrange': 'Mid-range hotel',
            'calcAccLuxury': 'Luxury hotel',
            'calcStyle': 'Travel style',
            'calcStyleBudget': 'Budget traveler',
            'calcStyleMidrange': 'Comfort traveler',
            'calcStyleLuxury': 'Luxury traveler',
            'calcIncludeFlight': 'Include estimated flights',
            'calcIncludeActivities': 'Include activities & tours',
            'calcReverseBudgetLabel': 'Maximum total budget',
            'calcReverseBudgetHint': 'Find countries that fit your total budget with your current settings (days, persons, style).',
            'calcFindByBudget': 'Find destinations by budget',
            'calcBudgetSearchTitle': 'Search destinations by budget',
            'calcBudgetSearchMatches': 'matches',
            'calcModeSelectorTitle': 'What would you like to do?',
            'calcModeSelectorSubtitle': 'Choose your planning mode to get started',
            'calcModeFind': 'Search by budget',
            'calcModeFindDesc': 'Enter your total budget and find matching destinations worldwide',
            'calcModeCalculate': 'Calculate trip budget',
            'calcModeCalculateDesc': 'Calculate the total cost for your planned trip step by step',
            'calcBackToModeSelect': 'Change mode',
            'calcReverseResultsTitle': 'Matching destinations',
            'calcReverseNoResults': 'No destination matches this budget with the selected settings.',
            'calcUseDestination': 'Use destination',
            'calcClearResults': 'Clear',
            'calcCalculate': 'Calculate budget',
            'calcReset': 'Reset',
            'calcResultTitle': 'Estimated budget',
            'calcPerPerson': 'per person',
            'calcTotal': 'Total',
            'calcPerDay': 'per day',
            'calcPerDayPerPerson': 'per day per person',
            'calcAccom': 'Accommodation',
            'calcFood': 'Food & drinks',
            'calcTransport': 'Local transport',
            'calcActivities': 'Activities & tours',
            'calcFlight': 'Flights',
            'calcBuffer': 'Safety buffer',
            'calcBookNow': 'Book now',
            'calcBookHotel': 'Search hotels',
            'calcBookFlight': 'Search flights',
            'calcBookActivities': 'Book activities',
            'calcBookAirbnb': 'Search on Airbnb',
            'calcDisclaimer': 'All amounts are rough estimates based on average travel costs. Actual costs may vary.',
            'calcCurrency': 'All prices in USD',
            'calcNightPP': 'per night/person',
            'calcDayPP': 'per day/person',
            'calcSubtitle': 'Plan your trip budget in seconds – choose a destination, set your style and get a full cost breakdown.',
            'calcTripPresets': 'Start with a preset',
            'calcPresetBackpacker': 'Backpacker',
            'calcPresetBackpackerDesc': 'Hostels, street food & local buses',
            'calcPresetComfort': 'Comfort',
            'calcPresetComfortDesc': 'Mid-range hotels & restaurants',
            'calcPresetLuxury': 'Luxury',
            'calcPresetLuxuryDesc': 'Premium hotels & fine dining',
            'calcPresetFamily': 'Family',
            'calcPresetFamilyDesc': 'Kid-friendly & all-inclusive',
            'calcPresetAdventure': 'Adventure',
            'calcPresetAdventureDesc': 'Active, outdoor & off-the-beaten-path',
            'calcInsights': 'Country Insights',
            'calcBestTime': 'Best time to visit',
            'calcLocalCurrency': 'Local currency',
            'calcMoneySaving': 'Money-saving tip',
            'calcOriginCountry': 'Start',
            'calcLargestCostDriver': 'Largest cost driver',
            'calcCostLevel': 'Trip level',
            'calcCostLevelValue': 'Value-focused',
            'calcCostLevelBalanced': 'Balanced comfort',
            'calcCostLevelPremium': 'Premium spend',
            'calcTierTitle': 'Budget tier comparison',
            'calcTierSubtitle': 'Estimated total for your trip at each level',
            'calcCompareBudget': 'Budget',
            'calcCompareMidrange': 'Mid-range',
            'calcCompareLuxury': 'Luxury',
            'calcFaqTitle': 'Frequently Asked Questions',
            'calcFaq1Q': 'How are the country and cost data generated?',
            'calcFaq1A': 'We combine free APIs with internal modelling. Countries and regions come from Rest Countries, economic signal data comes from World Bank GDP per capita (PPP), and then category prices (accommodation, food, transport, activities) are derived from calibrated factors and known benchmark destinations.',
            'calcFaq2Q': 'How is seasonality calculated from travel month?',
            'calcFaq2A': 'Seasonality is derived automatically from your selected travel month and the destination location (hemisphere/latitude). The calculator maps that to low, shoulder, or high season and applies multipliers to accommodation, food, transport and activities, while flights use a dedicated seasonal factor.',
            'calcFaq3Q': 'How are flight prices estimated?',
            'calcFaq3A': 'Flight estimates are distance-based: we calculate great-circle distance between origin and destination (Haversine), then apply a price curve by distance band and an accessibility factor for both countries. If geo data is unavailable, the calculator falls back to the legacy route-factor model.',
            'calcFaq4Q': 'How should I interpret the final total?',
            'calcFaq4A': 'The total is a planning estimate, not a live booking quote. It includes your selected trip profile and optional safety buffer for unexpected costs. Use it to compare destinations and scenarios quickly, then validate with live booking prices before final decisions.',
            'calcCalculating': 'Calculating...',
            'calcAffiliateDisclosure': 'Affiliate links. Prices can vary by date and availability.',
            'calcPriceAlertTitle': 'Price Alert',
            'calcPriceAlertText': 'Track flight and hotel deals for this destination before booking.',
            'calcPriceAlertButton': 'Set Alert',
            'calcWizardGuidedMode': 'Guided mode',
            'calcWizardFullFormMode': 'Full form',
            'calcWizardStepsAriaLabel': 'Budget guide steps',
            'calcWizardStepDestinations': 'Destinations',
            'calcWizardStepTripDetails': 'Trip details',
            'calcWizardStepBudgetSearch': 'Budget search',
            'calcWizardStepTravelStyle': 'Travel style',
            'calcWizardStepResult': 'Result',
            'calcWizardStepDesc1': 'Select a destination where you want to travel',
            'calcWizardStepDesc2': 'Enter trip details like duration and number of travelers',
            'calcWizardStepDesc3': 'Optionally search for destinations matching your budget',
            'calcWizardStepDesc4': 'Choose your travel style to adjust prices accordingly',
            'calcWizardStepDesc5': 'See your complete budget breakdown and booking links',
            'calcWizardStepHint1': 'Use filters or presets to find your destination',
            'calcWizardStepHint2': 'How long is your trip? How many people are traveling?',
            'calcWizardStepHint3': 'Set a maximum budget and find destinations that match your criteria',
            'calcWizardStepHint4': 'Budget, comfort or luxury? This affects accommodation and dining costs',
            'calcWizardStepHint5': 'Review the complete cost breakdown and start booking',
            'calcWizardContinueTripDetails': 'Continue to trip details',
            'calcWizardContinueBudgetSearch': 'Continue to budget search',
            'calcWizardContinueTravelStyle': 'Continue to travel style',
            'calcWizardContinueResult': 'Continue to result',
            'calcWizardSummaryTitle': 'Your setup',
            'calcWizardSummaryDestination': 'Destination',
            'calcWizardSummaryOrigin': 'Origin',
            'calcWizardSummaryDuration': 'Duration',
            'calcWizardSummaryDays': 'days',
            'calcWizardSummaryTravelers': 'Travelers',
            'calcWizardSummaryDisplayCurrency': 'Display currency',
            'calcWizardSummaryLocalCurrency': 'Local currency',

            // Footer
            'legal': 'Legal',
            'privacyPolicy': 'Privacy Policy',
            'copyright': 'All rights reserved',

            // Legal Page
            'impressum': 'Impressum',
            'termsOfService': 'Terms of Service',
            'legalInformation': 'Legal Information',
            'impressumDescription': 'Impressum, Privacy Policy & Terms of Service',

            // Home Page
            'myCareerPage': 'My career',
            'github': 'GitHub',
            'linkedin': 'LinkedIn',
            'toggleLanguage': 'Toggle Language',

            // Gallery
            'gallery': 'Gallery',
            'filter': 'Filter',
            'allPhotos': 'All Photos',
            'category': 'Category',
            'continent': 'Continent',
            'country': 'Country',
            'search': 'Search',
            'searchPlaceholder': 'Search by country, location, or keyword...',
            'page': 'Page',
            'of': 'of',
            'close': 'Close',
            'all': 'All',

            // Common
            'home': 'Home',
            'back': 'Back',
            'next': 'Next',
            'previous': 'Previous',
        },
        de: {
            // Header Navigation
            'aviation': 'Luftfahrt',
            'travel': 'Reisen',
            'photography': 'Fotografie',
            'myCareer': 'Mein CV',
            'buyPhotos': 'Meine Fotos auf Adobe Stock kaufen',
            'aviationGallery': 'Luftfahrt Galerie',
            'aviationSpotterHotels': 'Aviation Spotter Hotels',
            'airlineSim': 'AirlineSim',
            'airGermany': 'Air Germany',
            'airlineSimCeoTools': 'AirlineSim CEO Tools',
            'msfsComparison': 'MSFS Career Addons Vergleich',
            'travelInspiration': 'Reise Inspirationen',
            'travelGallery': 'Reise Galerie',
            'myVisitedCountries': 'Meine besuchten Länder',
            'menuDescTravelInspiration': 'Reise-Inspirationen von meinen Reisen',
            'menuDescVisitedCountries': 'Weltweite Reisekarte',
            'menuDescBudgetCalculator': 'Meine Reisekosten planen.',
            'searchByBudget': 'Reisen nach Budget suchen',
            'menuDescSearchByBudget': 'Finde Reiseziele, die in dein Budget passen',
            'menuDescAircraftPhotography': 'Flugzeugfotografie',
            'menuDescSpotterHotels': 'Die besten Spotting-Hotels',
            'menuDescMsfsComparison': 'Flugsimulator Vergleich',
            'menuDescAviationPhotography': 'Aviation-Fotografie',
            'menuDescTravelPhotography': 'Reisefotografie',
            'menuDescAdobeStock': 'Adobe Stock Portfolio',
            'menuDescBrowseProducts': 'Produkte durchstöbern',
            'menuDescAccountSettings': 'Account-Einstellungen',
            'menuDescDownloads': 'Heruntergeladene Dateien',
            'menuDescOrderHistory': 'Bestellhistorie',
            'shop': 'Shop',
            'myAccount': 'Mein Konto',
            'profile': 'Über mich',
            'experience': 'Erfahrung',
            'education': 'Ausbildung',
            'skills': 'Fähigkeiten',
            'projects': 'Projekte',
            'testimonials': 'Testimonials',

            // Career Page
            'downloadPDF': 'PDF Herunterladen',
            'viewCV': 'CV anzeigen',
            'skillsCertifications': 'Fähigkeiten & Zertifizierungen',
            'about': 'Über mich',
            'location': 'Standort',
            'email': 'E-Mail',
            'website': 'Webseite',
            'experiences': 'Erfahrung',
            'educations': 'Ausbildung',
            'certifications': 'Zertifizierungen',
            'languages': 'Sprachen',
            'skillsList': 'Fähigkeiten',
            'projectsList': 'Projekte',
            'testimonialsList': 'Testimonials',
            'native': 'Muttersprache',
            'fluent': 'Fließend',
            'technologies': 'Technologien',
            'duration': 'Dauer',
            'process': 'Vorgehensweise',
            'teamExperience': 'Team-Erfahrung',
            'liveTest': 'Live-Test',
            'whatColleaguesSay': 'Das sagen Kollegen',
            'projectLabel': 'Projekt:',

            // Footer
            'legal': 'Rechtliches',
            'privacyPolicy': 'Datenschutz',
            'copyright': 'Alle Rechte vorbehalten',

            // Legal Page
            'impressum': 'Impressum',
            'termsOfService': 'Nutzungsbedingungen',
            'legalInformation': 'Rechtliche Informationen',
            'impressumDescription': 'Impressum, Datenschutz & Nutzungsbedingungen',

            // Home Page
            'myCareerPage': 'Meine Karriere',
            'github': 'GitHub',
            'linkedin': 'LinkedIn',
            'toggleLanguage': 'Sprache wechseln',

            // Gallery
            'gallery': 'Galerie',
            'filter': 'Filter',
            'allPhotos': 'Alle Fotos',
            'category': 'Kategorie',
            'continent': 'Kontinent',
            'country': 'Land',
            'search': 'Suchen',
            'searchPlaceholder': 'Suche nach Land, Ort oder Stichwort...',
            'page': 'Seite',
            'of': 'von',
            'close': 'Schließen',
            'all': 'Alle',

            // Common
            'home': 'Startseite',
            'back': 'Zurück',
            'next': 'Weiter',
            'previous': 'Zurück',

            // Budget Calculator
            'budgetCalculator': 'Reisebudget-Rechner',
            'calcDestination': 'Reiseziel',
            'calcStartCountry': 'Startland',
            'calcSelectStartCountry': 'Abflugland auswählen...',
            'calcSelectCountry': 'Land auswählen...',
            'calcDuration': 'Reisedauer (Tage)',
            'calcPersons': 'Anzahl Personen',
            'calcDisplayCurrency': 'Anzeigewährung',
            'calcSeasonLabel': 'Reisesaison',
            'calcSeasonLow': 'Nebensaison (günstiger)',
            'calcSeasonShoulder': 'Zwischensaison (ausgewogen)',
            'calcSeasonHigh': 'Hauptsaison (Hochpreise)',
            'calcSeasonHint': 'Die Saison beeinflusst Unterkunfts-, Aktivitäts- und Flugkosten.',
            'calcSeasonUnknown': 'Saison nicht verfuegbar',
            'calcTravelMonthLabel': 'Reisemonat',
            'calcTravelMonthHint': 'Waehle deinen Reisemonat. Die Saison wird fuer das Zielland automatisch abgeleitet.',
            'calcDerivedSeasonLabel': 'Ermittelte Saison',
            'calcBufferPercent': 'Sicherheitspuffer',
            'calcAccommodation': 'Unterkunft',
            'calcAccBudget': 'Budget (Hostel / Gästehaus)',
            'calcAccMidrange': 'Mittelklasse-Hotel',
            'calcAccLuxury': 'Luxus-Hotel',
            'calcStyle': 'Reisestil',
            'calcStyleBudget': 'Budget-Reisender',
            'calcStyleMidrange': 'Komfort-Reisender',
            'calcStyleLuxury': 'Luxus-Reisender',
            'calcIncludeFlight': 'Geschätzte Flüge einrechnen',
            'calcIncludeActivities': 'Aktivitäten & Touren einrechnen',
            'calcReverseBudgetLabel': 'Maximales Gesamtbudget',
            'calcReverseBudgetHint': 'Finde Länder, die mit deinen aktuellen Einstellungen (Tage, Personen, Stil) in dein Budget passen.',
            'calcFindByBudget': 'Reiseziele nach Budget finden',
            'calcBudgetSearchTitle': 'Reiseziele nach Budget suchen',
            'calcBudgetSearchMatches': 'Treffer',
            'calcModeSelectorTitle': 'Was möchtest du tun?',
            'calcModeSelectorSubtitle': 'Wähle deinen Planungsmodus, um loszulegen',
            'calcModeFind': 'Nach Budget suchen',
            'calcModeFindDesc': 'Gib dein Gesamtbudget ein und finde passende Reiseziele weltweit',
            'calcModeCalculate': 'Reisebudget kalkulieren',
            'calcModeCalculateDesc': 'Berechne die Gesamtkosten für deine geplante Reise Schritt für Schritt',
            'calcBackToModeSelect': 'Modus wechseln',
            'calcReverseResultsTitle': 'Passende Reiseziele',
            'calcReverseNoResults': 'Mit den gewählten Einstellungen passt kein Reiseziel in dieses Budget.',
            'calcUseDestination': 'Als Ziel nutzen',
            'calcClearResults': 'Leeren',
            'calcCalculate': 'Budget berechnen',
            'calcReset': 'Zurücksetzen',
            'calcResultTitle': 'Geschätztes Budget',
            'calcPerPerson': 'pro Person',
            'calcTotal': 'Gesamt',
            'calcPerDay': 'pro Tag',
            'calcPerDayPerPerson': 'pro Tag pro Person',
            'calcAccom': 'Unterkunft',
            'calcFood': 'Essen & Trinken',
            'calcTransport': 'Lokaler Transport',
            'calcActivities': 'Aktivitäten & Touren',
            'calcFlight': 'Flüge',
            'calcBuffer': 'Sicherheitspuffer',
            'calcBookNow': 'Jetzt buchen',
            'calcBookHotel': 'Hotels suchen',
            'calcBookFlight': 'Flüge suchen',
            'calcBookActivities': 'Aktivitäten buchen',
            'calcBookAirbnb': 'Bei Airbnb suchen',
            'calcDisclaimer': 'Alle Beträge sind grobe Schätzwerte auf Basis durchschnittlicher Reisekosten. Tatsächliche Kosten können abweichen.',
            'calcCurrency': 'Alle Preise in USD',
            'calcNightPP': 'pro Nacht/Person',
            'calcDayPP': 'pro Tag/Person',
            'calcSubtitle': 'Plane dein Reisebudget in Sekunden – wähle ein Ziel, definiere deinen Stil und erhalte eine detaillierte Kostenübersicht.',
            'calcTripPresets': 'Mit Vorlage starten',
            'calcPresetBackpacker': 'Backpacker',
            'calcPresetBackpackerDesc': 'Hostels, Streetfood & Nahverkehr',
            'calcPresetComfort': 'Komfort',
            'calcPresetComfortDesc': 'Mittelklasse-Hotels & Restaurants',
            'calcPresetLuxury': 'Luxus',
            'calcPresetLuxuryDesc': 'Premium Hotels & Fine Dining',
            'calcPresetFamily': 'Familie',
            'calcPresetFamilyDesc': 'Kinderfreundlich & All-Inclusive',
            'calcPresetAdventure': 'Abenteuer',
            'calcPresetAdventureDesc': 'Aktiv, outdoor & abseits der Touristenpfade',
            'calcInsights': 'Länder-Infos',
            'calcBestTime': 'Beste Reisezeit',
            'calcLocalCurrency': 'Währung',
            'calcMoneySaving': 'Spartipp',
            'calcOriginCountry': 'Start',
            'calcLargestCostDriver': 'Größter Kostenblock',
            'calcCostLevel': 'Reiseniveau',
            'calcCostLevelValue': 'Preisbewusst',
            'calcCostLevelBalanced': 'Ausgewogen',
            'calcCostLevelPremium': 'Premium',
            'calcTierTitle': 'Budget-Tier-Vergleich',
            'calcTierSubtitle': 'Geschätzte Gesamtkosten je Reiseniveau',
            'calcCompareBudget': 'Budget',
            'calcCompareMidrange': 'Mittelklasse',
            'calcCompareLuxury': 'Luxus',
            'calcFaqTitle': 'Häufig gestellte Fragen',
            'calcFaq1Q': 'Wie werden Länder- und Kostendaten berechnet?',
            'calcFaq1A': 'Wir kombinieren kostenfreie APIs mit internem Modell. Länder und Regionen kommen von Rest Countries, das wirtschaftliche Signal von World Bank GDP pro Kopf (PPP), und daraus werden Kategoriepreise (Unterkunft, Essen, Transport, Aktivitäten) über kalibrierte Faktoren und bekannte Benchmark-Ziele abgeleitet.',
            'calcFaq2Q': 'Wie wird die Saisonalitaet aus dem Reisemonat berechnet?',
            'calcFaq2A': 'Die Saisonalitaet wird automatisch aus deinem Reisemonat und der Lage des Ziellandes (Hemisphaere/Breitengrad) abgeleitet. Daraus ergibt sich Nebensaison, Zwischensaison oder Hauptsaison mit entsprechenden Multiplikatoren fuer Unterkunft, Essen, Transport und Aktivitaeten; Fluege nutzen zusaetzlich einen eigenen Saisonfaktor.',
            'calcFaq3Q': 'Wie werden Flugpreise geschätzt?',
            'calcFaq3A': 'Die Flugschätzung ist distanzbasiert: Wir berechnen die Großkreisdistanz zwischen Start- und Zielland (Haversine), nutzen danach eine Preisfunktion je Distanzband und einen Erreichbarkeitsfaktor beider Länder. Fehlen Geodaten, nutzen wir ein Fallback-Modell mit Routenfaktoren.',
            'calcFaq4Q': 'Wie ist der Gesamtbetrag zu verstehen?',
            'calcFaq4A': 'Der Gesamtwert ist eine Planungs-Schätzung, kein Live-Buchungspreis. Er enthält dein gewähltes Reiseprofil und optional den Sicherheitspuffer für ungeplante Ausgaben. Nutze ihn für schnelle Zielvergleiche und prüfe finale Preise anschließend mit Live-Angeboten.',
            'calcCalculating': 'Berechnung läuft...',
            'calcAffiliateDisclosure': 'Affiliate-Links. Preise können je nach Datum und Verfügbarkeit variieren.',
            'calcPriceAlertTitle': 'Preisalarm',
            'calcPriceAlertText': 'Verfolge Flug- und Hotelangebote für dieses Reiseziel vor der Buchung.',
            'calcPriceAlertButton': 'Alarm setzen',
            'calcWizardGuidedMode': 'Gefuehrter Modus',
            'calcWizardFullFormMode': 'Vollansicht',
            'calcWizardStepsAriaLabel': 'Budget Guide Schritte',
            'calcWizardStepDestinations': 'Ziele',
            'calcWizardStepTripDetails': 'Reisedaten',
            'calcWizardStepBudgetSearch': 'Budgetsuche',
            'calcWizardStepTravelStyle': 'Reisestil',
            'calcWizardStepResult': 'Ergebnis',
            'calcWizardStepDesc1': 'Wähle eine Destination für deine nächste Reise',
            'calcWizardStepDesc2': 'Gib Reisedaten ein wie Dauer und Anzahl der Reisenden',
            'calcWizardStepDesc3': 'Suche nach Destinationen die deinem Budget entsprechen',
            'calcWizardStepDesc4': 'Wähle deinen Reisestil um Preise anzupassen',
            'calcWizardStepDesc5': 'Sieh dir deine komplette Budget-Übersicht und Links an',
            'calcWizardStepHint1': 'Nutze Filter oder Vorlagen um dein Reiseziel zu finden',
            'calcWizardStepHint2': 'Wie lange ist deine Reise? Mit wie vielen Personen reist du?',
            'calcWizardStepHint3': 'Lege ein maximales Budget fest und finde passende Ziele',
            'calcWizardStepHint4': 'Budget, Komfort oder Luxus? Das beeinflusst Unterkunft und Essen',
            'calcWizardStepHint5': 'Überprüfe die Gesamtkostenaufschlüsselung und starte mit Buchen',
            'calcWizardContinueTripDetails': 'Weiter zu Reisedaten',
            'calcWizardContinueBudgetSearch': 'Weiter zur Budgetsuche',
            'calcWizardContinueTravelStyle': 'Weiter zum Reisestil',
            'calcWizardContinueResult': 'Weiter zum Ergebnis',
            'calcWizardSummaryTitle': 'Deine Auswahl',
            'calcWizardSummaryDestination': 'Ziel',
            'calcWizardSummaryOrigin': 'Startland',
            'calcWizardSummaryDuration': 'Dauer',
            'calcWizardSummaryDays': 'Tage',
            'calcWizardSummaryTravelers': 'Personen',
            'calcWizardSummaryDisplayCurrency': 'Anzeigewaehrung',
            'calcWizardSummaryLocalCurrency': 'Landeswaehrung',
        }
    };
}
